import type { Metadata } from "next";
import Link from 'next/link';
import "./globals.css";
import Image from 'next/image';

export const metadata: Metadata = {
  title: "FinTrack",
  description: "Generated by Tatin",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#F9F5EF]">
         <header>
          <div className="navbar">
            <ul className="main-nav flex items-center gap-7 ml-4 mt-2">
              <li>
                <Link href='/'>
                  <Image src='/logo.png' alt='logo' width={55} height={50}/>
                </Link>
              </li>
              <li>
                  <Link href='/' className='text-sm font-medium text-foreground/80 hover:text-foreground transition-colors relative group'>
                  Home
                  <span className="absolute bottom-[-3px] left-0 w-0 h-0.5 bg-gradient-to-r from-green-400 to-green-600 group-hover:w-full transition-all duration-300"/>
                  </Link>
              </li>
              <li>
                <Link href='/about' className='text-sm font-medium text-foreground/80 hover:text-foreground transition-colors relative group'>
                  About Us
                  <span className="absolute bottom-[-3px] left-0 w-0 h-0.5 bg-gradient-to-r from-green-400 to-green-600 group-hover:w-full transition-all duration-300"/>
                  </Link>
              </li>
              <li>
                <Link href='/contacts' className='text-sm font-medium text-foreground/80 hover:text-foreground transition-colors relative group'>
                  Contact Us
                  <span className="absolute bottom-[-3px] left-0 w-0 h-0.5 bg-gradient-to-r from-green-400 to-green-600 group-hover:w-full transition-all duration-300"/>
                  </Link>
              </li>
            </ul>
            <ul className="sidenav">
              <li>

              </li>
            </ul>
          </div>
        </header>
        {children}
        <footer>

        </footer>
      </body>
    </html>
  );
}
