import type { Metadata } from "next";
import Link from 'next/link';
import "./globals.css";
import Image from 'next/image';
import { ThemeProvider } from "next-themes";
import { ThemeToggle } from "@/app/themetoggle";
import NavBar from "@/components/navbar";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "FinTrack",
  description: "Generated by Tatin",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
        <body className="bg-[#F9F5EF] dark:bg-black">
          <ThemeProvider attribute="class" enableSystem defaultTheme="system">
            <div className="bg-[#F9F5EF] text-[#1B3A2F] dark:bg-black dark:text-white transition-all duration-400">
              <NavBar></NavBar>
              <div className="min-h-screen">
                {children}
              </div>
              <Footer></Footer>
            </div>
          </ThemeProvider>
        </body>
    </html>
  );
}
